### ISSUE TITLE
Not compiling when used with PostCSS

### ISSUE THREAD

**Issue by danwetherald** [benface/tailwindcss-transitions#11]
When configured to use PostCSS, thee plugin doesn't seem to run.

**Comment by benface** [comment]
@dan003400 Could you please provide me an example repo so I can reproduce this issue?

**Comment by danwetherald** [comment]
Started a fresh CRA and it worked perfectly, implemented it the same way in my app and now I see the classes being compiled to tailwind.css

I am not 100% sure what has changed, but it seems to be working now.

Thanks
