### ISSUE TITLE
No Copyright Licence

### ISSUE THREAD

**Issue by BobanStanojevicST** [benface/tailwindcss-transitions#12]
Hi,

I found your project it completely solves my problems but to use it on the project that I'm working on I need to have a copyright licence, do you think it could be possible to add it to the project? 

>  You're under no obligation to choose a license. However, without a license, the default copyright laws apply, meaning that you retain all rights to your source code and no one may reproduce, distribute, or create derivative works from your work. If you're creating an open source project, we strongly encourage you to include an open source license. The Open Source Guide provides additional guidance on choosing the correct license for your project. 

[https://help.github.com/en/articles/licensing-a-repository](https://help.github.com/en/articles/licensing-a-repository)

Thanks in advance, cheers

**Comment by hacknug** [comment]
Licensed under [ISC](https://en.wikipedia.org/wiki/ISC_license) according to [`package.json`](https://github.com/benface/tailwindcss-transitions/blob/master/package.json#L6)

**Comment by BobanStanojevicST** [comment]
It would be nice to follow [Github's best practice](https://help.github.com/en/articles/licensing-a-repository#determining-the-location-of-your-license) and also include the license into the root of the project, if possible.

**Comment by benface** [comment]
Done in https://github.com/benface/tailwindcss-transitions/commit/4cdd4970311089b0b319e38122977f32e1c57002, thanks!
