### ISSUE TITLE
Apply transition with custom components [@apply]

### ISSUE THREAD

**Issue by sanderjson** [benface/tailwindcss-transitions#13]
Is` there a way to apply the transition to extracted css classes with [@apply]?
 
```
.btn {
    @apply bg-indigo-600 text-indigo-100;
}

.btn:hover {
    @apply bg-indigo-300 text-indigo-900;
}

/* .btn transition 
transition-bg transition-text
*/
```

**Comment by benface** [comment]
@sanderjson Yes, you should be able to do that, but contrarily to using classes in the markup, the order of classes in `@apply` matters. Make sure to put the `transition-[property]` utility before any `transition-[duration]`, `transition-[timing-function]`, or `transition-delay-*` utility. For instance:

```css
.btn {
  @apply transition-bg transition-500;
}
```
