### ISSUE TITLE
Is it possible to change the default class that is created?

### ISSUE THREAD

**Issue by dymond** [benface/tailwindcss-transitions#2]
I frequently utilize `:before` and `:after` to generate gradient animations. I believe there should be an option to add those selectors into `baseStyles`. It's not a huge deal, but I'm used to only declaring `transition-all` so I almost always forget to on these classes.

I personally think the default should be `*, *::before, *::after`. I believe that would get all visual elements where a transition is possible.

**Comment by benface** [comment]
It cannot be changed, but you're right that the default should be `*, *::before, *::after`. Fixed in [v2.0.1](https://github.com/benface/tailwindcss-transitions/releases/tag/v2.0.1). Thank you!
