### ISSUE TITLE
global default transition-property & transition-duration aren't utility-first

### ISSUE THREAD

**Issue by lockinmarv** [benface/tailwindcss-transitions#7]
tailwindcss-transitions sets base styles for transition-property & transition-duration like this:
```
*, *::before, *::after {
  transition-property: none;
  transition-duration: 250ms;
}
```

In my opinion it's against utility-first because every element gets those base styles even though they may not even need it. And that might cause an uncontrollable behavior in some cases.

Is there a better approch for this?

**Comment by hacknug** [comment]
Have you seen #3?

**Comment by lockinmarv** [comment]
> Have you seen #3?

Sounds like the same problem, thanks :)
